### ISSUE TITLE
Create app with basic routes

### ISSUE THREAD

**Issue by AHDesigns** [playful-panda/munch#1]
## Task outline

We need a starting point to build off. Most of this can be done roughly, just to get the ball rolling.

### AC
- [x] create-react-app to spin up project
- [x] set up folder structure as per below
- [x] Using react-router, add pages (each page can just be a blank page with the word of the page on it):
  - [x] welcome (url `/welcome`)
  - [x] home (url `/`)
  - [x] error ( url `/error`)
- [x] add a simple navigation bar that is visible on all pages and can move the user between the above pages
- [x] user can 'deeplink' into all pages by changing the url manually (i.e typing localhost:3000/welcome)
- [x] on typing an incorrect url, user is redirected to `/home`

---

## Additional Info

Folder Structure

```
- src/
  - index.js
  - App.jsx
  - pages/
    - Welcome.jsx
    - Error.jsx
    - Home.jsx
```
