### ISSUE TITLE
Add Storybook

### ISSUE THREAD

**Issue by AHDesigns** [playful-panda/munch#2]
## Task outline

Add Storybook to app.

### AC
 - [x] install storybook and save the command to the `package.json` as `storybook`, so that a dev can run storybook by typing `yarn storybook`.
- [x] create a button component and show it ONLY in storybook, do not add it to a page for now. The `Button` must support the following props:
  - [x] `text`: controls the message on the button
  - [x] `modifier`: must be a string of `primary` or `secondary` to change colour of button
  - [x] `clickHandler`: a callback function to be invoked when clicked
- [x] update the folder structure as shown below
- [x] add the [actions](https://github.com/storybookjs/storybook/tree/master/addons/actions) addon.
  - [x] show an 'action' using this addon, when the `Button` component is clicked
- [x] add the [knobs](https://github.com/storybookjs/storybook/tree/master/addons/knobs) addon.
  - [x] use the 'knobs' to control the `text` prop of the `Button`

---

## Additional Info

The docs for installation can be found [here](https://storybook.js.org/docs/guides/guide-react/#automatic-setup) and they are pretty friendly. It looks like `Automatic setup` section should be enough, as we are using create-react-app (which is using `react-scripts` referenced in the storybook documentation and you can see this if you look in the `package.json` of the "munch" app)

I'm not sure where this default setup will expect 'story' files to go. 

Ideally add the following folders and files:
```
- src/
  - components/
    - Button/
      index.js (which will contain all the code for the button)
      style.module.css
      story.js (which will contain the story, and import the button component from `index.js`)
```
(notice the **name** of `style.module.css` see [here](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet) for rational)
