### ISSUE TITLE
Create Form Field atom

### ISSUE THREAD

**Issue by codethread** [playful-panda/munch#4]
## Task outline
Create a form field atom that can be used for forms.

### AC
 - [x] shows placeholder
 - [ ] placeholder moves, or appears in smaller print once field is entered
 - [x] field can be a 'password', which displays `*` for keys
 - [ ] field supports validations:
   - [x] validation starts in text colour until the condition has been met
   - [ ] validation goes red when the client tries to submit the form
   - [ ] validation goes from red to green when the condition is met

---

## Additional Info

[design link: Pages > Atoms > Form Fields](https://www.figma.com/file/FE5f1uQnRNwkBUzEROteAg/Munch?node-id=13%3A0)

![image](https://user-images.githubusercontent.com/10004500/84313748-e9711800-ab5e-11ea-979a-16c902cd4fa1.png)
